monolog:
    channels: ["commandes", "utilisateurs"]
    handlers:
        order:
            type: stream
            path: "%kernel.logs_dir%/order.log"
            level: info
            channels: ["commandes"]

        user:
            type: stream
            path: "%kernel.logs_dir%/user.log"
            level: info
            channels: ["utilisateurs"]
